version: '3.6'

services:
    db:
        image: mysql:5.7
        volumes:
          - data_db:/var/lib/mysql
        networks:
            - group1
        ports:
            - 2319:3306
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: wordpress1
            MYSQL_USER: wordpress1
            MYSQL_PASSWORD: ${MYSQL_WORDPRESS1_PASSWORD}

    wordpress:
        image: wordpress:latest
        depends_on:
            - db
        networks:
            - group1
        #ports:
        #    - 581:80
        restart: always
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_NAME: wordpress1
            WORDPRESS_DB_USER: wordpress1
            WORDPRESS_DB_PASSWORD: ${MYSQL_WORDPRESS1_PASSWORD}
        volumes:
            - .fs-overlays/plugins:/var/www/html/wp-content/plugins
            - .fs-overlays/themes:/var/www/html/wp-content/themes
            - .fs-overlays/uploads:/var/www/html/wp-content/uploads
volumes:
    data_db:

networks:
    group1:
        name: group1
        driver: bridge
