version: "3.3"

services:
  proxy:
    container_name: 'proxy'
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config:/config
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /tmp/acme_challenge:/tmp/acme_challenge
    networks:
      - group1
    restart: always

networks:
    group1:
        name: group1
        driver: bridge
        external: true
